# Funding options for free-ai-agents-resources
# This file enables the "Sponsor" button on GitHub

# GitHub Sponsors
github: avinash201199

# Custom sponsorship platforms
custom: ["https://paypal.me/Avinash425"]
